// Feature flags for optional template add-ons (Buchung, Galerie, WhatsApp,
// Analytics). Generated by `npm run setup` — rerun the wizard to change
// these values instead of hand-editing, so this file and the CLIENT.md
// answers stay in sync.

export interface FeatureConfig {
  /** Renders the reference/portfolio gallery on the homepage and /projekte. */
  gallery: boolean;
  /** Links to an external booking tool (Calendly, cal.com, …). */
  booking: { enabled: boolean; url: string };
  /** Floating WhatsApp contact button, visible on every page. */
  whatsapp: { enabled: boolean; number: string };
  /** Vercel Analytics + Speed Insights, gated behind the cookie consent banner. */
  analytics: boolean;
}

export const features: FeatureConfig = {
  gallery: false,
  booking: { enabled: false, url: "" },
  whatsapp: { enabled: false, number: "" },
  analytics: false,
};
