// Feature flags for optional template add-ons (Buchung, Galerie, WhatsApp).
// Generated by `npm run setup` — rerun the wizard to change these values
// instead of hand-editing, so this file and the CLIENT.md answers stay in sync.

export interface FeatureConfig {
  /** Renders the reference/portfolio gallery on the homepage. */
  gallery: boolean;
  /** Links to an external booking tool (Calendly, cal.com, …). */
  booking: { enabled: boolean; url: string };
  /** Floating WhatsApp contact button, visible on every page. */
  whatsapp: { enabled: boolean; number: string };
}

export const features: FeatureConfig = {
  gallery: false,
  booking: { enabled: false, url: "" },
  whatsapp: { enabled: false, number: "" },
};
